### ISSUE TITLE
[BUG] Default config creates a open relay on baremetal

### ISSUE THREAD

**Issue by yelhouti** [Mailu/helm-charts#93] opened 2021-05-29 04:20 UTC
**Describe the bug**
When I install mailu, and I check the logs of mailu-front all requests seems to come from cni0 ip address because of the use of hostPort. This ip is forwarded to postfix making it an open relay.
is there a specific raison for having an nginx inside k8s ? IMO, communication between pods should be done using service name (each deployment with its own service) 
1. it would make it clear what depends on what, and what talks to what.
1. it would allow to use hostNetwork when we want to expose something (smtp, imap...) removing the need for hostPort and reducing the risk of intermediaries creating open relays (ex: mis-config of nginx).

**Environment**
 - Kubespray
 - flannel
 
**Additional context**

**Comment by micw** [comment] 2021-05-29 09:07
Hello,
nginx is used smtp/imap/pop3. It preserves the originating IP. I run exactly this setup and it's not an open relay. Check that the original IP is in nginx logs. If not, your k8s setup is somehow broken.

**Comment by yelhouti** [comment] 2021-05-29 12:30
@micw which CNI are using? Maybe the problem is specific to flannel.

**Comment by yelhouti** [comment] 2021-06-02 22:48
@micw the problems seems to happen when kube-proxy is configured with iptables mode instead of ipvs. don't know if we have a way to prevent that, but we should definitely document it and tell people how to test if they operate an open relay. since this can severely impact IP/RANGE score...

**Comment by micw** [comment] 2021-06-03 05:49
I use canal with default setup (as provided by rancher2).
If your CNI makes your pods see internal IPs for external traffic, it should be considered seriously broken. With mail, you see consequences very directly (spam, bad reputation) but such an issue would also affect other services that rely on ip information (e.g. any rate-limiting stuff, session security of several applications).

Nevertheless, IMO that's not a bug in mailu or the helm chart. It needs to be fixed in the CNI config.

**Closed** 2021-06-28 19:44 UTC
Labels: bug
