### ISSUE TITLE
mailu 2.0.30 ate mail, unknown reason, might be misconfig

### ISSUE THREAD

**Issue by christf** [Mailu/helm-charts#311] opened 2023-10-21 18:20 UTC
I am using mailu 2.0.30 from helm chart and recently upgraded from 2.0.29. Since the upgrade mails were fetched with fetchmail, removed from the upstream account but never hit the mailbox in dovecot. This may entirely be my fault due to misconfiguration. In the meantime I disabled fetchmail for now to avoid any further mail disappear.  

At this point I am looking for help to identify the problem. What should I check?
Is this even the right repository (since I deployed with helm)?

**Comment by christf** [comment] 2023-10-24 19:30
I am using the chart from here https://mailu.github.io/helm-charts/ and setting  `mailuVersion: 2.0.30` . There have been multiple changes so I am uncertain whether it happened at the same time like bumping the version but the referenced issue #309 seems to describe the same symptom.

If that is it, then there may be something around unmet implicit expectations when using the chart or the application version. So let me lay out my thought process and how I ended up raising an issue in this particular tracker. Maybe that will provide something useful that could be put into the documentation (will be happy to raise PR, if we indeed find this to be helpful) to guide users in the future. Anyway, here it goes:

* I consider an application a deployable unit. Applications need to be versioned such that they can be upgraded and their state tracked.
* I consider a helm chart a software artefact that describes how something (an application) is to be deployed. Over time the description might change even though the same version of in the application is to be deployed. As such it is my implicit expectation that the helm chart version (the description of the deployment) is different and decoupled from the application version (thing I actually want to use).
* When utilizing versions that way, I hope to achieve repeatable deployments and inherent rollback capabilities. I also obtain the ability to use something like renovate to notify me of upgrades.

This is how I approached the project and the chart. Since I saw "a container not becoming healthy" I assumed it must be an issue with the application and turned here for the bug report.

From what I have read in the last few hours, it seems that the mailu helmchart does not work that way. I have come to understand that this helm chart and the application itself form a unit. The chart in version 1.4.0 is meant to deploy mailu in version 2.0.22. That's it. Whenever a new helm chart update is done, the mailu version may be bumped and then there might be a helm chart version 1.5.0 that deploys mailu 2.0.x and is meant to deploy only that version.

Is this understanding correct?

**Comment by fastlorenzo** [comment] 2023-10-24 19:55
@christf I've posted a workaround for the issue in #309 
The problem is that a check was introduced in Mailu to avoid having people reporting issues when using "non supported" ways of deploying Mailu (meaning, not using docker-compose or this helm chart).
However, the side effect is that this check only took into consideration users having a docker runtime. Meaning that people like you (I assume) and me that have a different runtime in k8s (mine being containerd) and are using this chart have ended up in a boot loop of the admin container.

The chart has a specific version of Mailu set as default in the values file (current version is `2.0.20`), meaning this is the last version the chart was tested against Mailu.
This variable can be overridden by the user to deploy another Mailu version.
Normally, you should be able to safely upgrade the Mailu version in there without upgrading the chart (for example, if you see the default value in the chart isn't at the latest Mailu version yet).

I'm working on a new release of this chart that will temporarily set the `I_KNOW_MY_SETUP_DOESNT_FIT_REQUIREMENTS_AND_WONT_FILE_ISSUES_WITHOUT_PATCHES` env var so people can safely upgrade if they are not using a docker runtime as a workaround.

A long term solution will be to have a specific environment variable set in all containers when using the chart so there is an easy way to check if the deployment, if not using a docker runtime, has been done using this chart and is thus a supported deployment model.

I'll close this issue in favor of #309

**Closed by fastlorenzo** 2023-10-24 19:55 UTC

**Comment by christf** [comment] 2023-10-24 19:58
ok, so this is a missing feature in the chart then, allowing for upgrades beyond a certain version of mailu. Thank you for addressing that! :+1:

**Comment by fastlorenzo** [comment] 2023-10-24 20:07
> Can you confirm whether the emails are definitely gone upstream or whether they have just been marked as "seen" by fetchmail ?

@christf could you please answer this question? because if the emails are gone, this shouldn't happen if the emails have not been accepted by Mailu

**Comment by christf** [comment] 2023-10-24 20:45
this was resolved with chart release 1.5.0
