### ISSUE TITLE
Helm-charts are missing newly introduced environment variables

### ISSUE THREAD

**Issue by Diman0** [Mailu/helm-charts#123] opened 2021-11-15 09:29 UTC
The helm-chart is not in sync with the mailu.env file. At least these environment variables must be added
- REAL_IP_FROM
- REAL_IP_HEADER
See https://mailu.io/master/configuration.html#reverse-proxy-headers for more information.  These env variables are used by front (nginx).

These are introduced on master. If these settings are not configured in Mailu, then Mailu will not trust (use) the client IP that is provided by the reverse proxy. 

I think it is a good idea to also check other env variables in the [mailu.env file[(https://mailu.io/master/configuration.html). Multiple environment variables have been added this year.

**Comment by micw** [comment] 2021-11-15 09:39
There's also ADMIN_ADDRESS in rspamd:
https://github.com/Mailu/helm-charts/pull/119

are there any more?

**Comment by HaleyACS** [comment] 2021-11-15 10:25
ADMIN_ADDRESS is existing in dovecot, front and postfix in my current 1.8 deployment. Chances are this is handled correctly with 1.9.
It will need to be added in rspamd config though.

REAL_IP_HEADER and REAL_IP_FROM are already handled in front 1.8.

**Comment by Diman0** [comment] 2021-11-15 10:57
These are a list of env variables that were added recently (at least I think so):
- WILDCARD_SENDERS
- AUTH_RATELIMIT_USER
- AUTH_RATELIMIT_EXEMPTION
- MESSAGE_RATELIMIT
- MESSAGE_RATELIMIT_EXEMPTION
- OUTBOUND_TLS_LEVEL
- DEFER_ON_TLS_ERROR
- INBOUND_TLS_ENFORCE
- CREDENTIAL_ROUNDS
- SESSION_COOKIE_SECURE
- SESSION_LIFETIME
- LETSENCRYPT_SHORTCHAIN
- TZ

All the settings are documented in configuration reference. Most of them have proper default values. 

What is also important is that rspamd needs a **static** hostname. If the hostname is not static, then history is not retained. This is a limitation of rspamd. Possibly the helm-chart already does this. I did not check this.

**Comment by micw** [comment] 2021-11-15 11:03
Great, thank you. We need to check which are mantadory for 1.9 to replace an existing 1.8. these should be added by one of the next PRs. For the other we can do feature PRs independently.

**Comment by micw** [comment] 2021-11-15 11:04
"TZ" is great. I have a workaround by mounting stuff from the host in the chart which can be removed then. Need to check if it was backported.

**Comment by HaleyACS** [comment] 2021-11-15 12:11
> What is also important is that rspamd needs a **static** hostname. If the hostname is not static, then history is not retained on container recreation. This is a limitation of rspamd. Possibly the helm-chart already does this. I did not check this.

Nope. The helm-chart does not take that into account.
That would require 1 thing to be changed, and 1 to be added.
`apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mailu-rspamd
  namespace: mailu-mailserver  
spec:
  serviceName: "mailu-rspamd"
  selector:
    matchLabels:
      app: mailu
      component: rspamd
`
The Kind needs to be changed to "StatefulSet", and we need to add the serviceName to be something.

**Comment by Diman0** [comment] 2021-11-15 12:33
It looks like not all mappings are  in sync.
https://github.com/Mailu/helm-charts/blob/e8dd5bebdec84003a64bf86adb24e65ec6563d79/mailu/templates/rspamd.yaml#L43
This is not required anymore (rspamd does not need access to /dkim).
Rspamd (in helm-chart) misses the mapping "{{ root }}/overrides/rspamd:/etc/rspamd/override.d:ro"

Just for completeness. This is the current host mapping ( local file system:path on docker image) on master. Maybe you can double check this in the helm-charts as well? 
{{ root }} is the chosen data folder. For default installations this is /mailu.
- front (ningx):
  - volumes:
    - "{{ root }}/certs:/certs"
    - "{{ root }}/overrides/nginx:/overrides:ro"
- admin
   - volumes:
      - "{{ root }}/data:/data"
      - "{{ root }}/dkim:/dkim"
- imap (dovecot)
  -  volumes:
      - "{{ root }}/mail:/mail"
      - "{{ root }}/overrides/dovecot:/overrides:ro"
- smtp (postfix)
  - volumes:
      - "{{ root }}/mailqueue:/queue"
      - "{{ root }}/overrides/postfix:/overrides:ro"
- antispam (rspamd)
  - volumes:
      - "{{ root }}/filter:/var/lib/rspamd"
      - "{{ root }}/overrides/rspamd:/etc/rspamd/override.d:ro"
- antivirus (clamav)
  - volumes:
      - "{{ root }}/filter:/data"
- webdav (radicale)
  - volumes:
      - "{{ root }}/dav:/data"
- fetchmail
  - volumes:
      - "{{ root }}/data/fetchmail:/data"
- webmail
  - volumes:
      - "{{ root }}/webmail:/data"

**Comment by HaleyACS** [comment] 2021-11-15 12:58
If I start a pristine mailu installation with a helm-chart, everything that points to /data is held in a persistent storage. All the rest, is not. 
So as /data is defined, everything is in there. But rspamd local configuration as in /etc/rspamd/local.d is not. I bet that applies also for docker-compose style setup. 
When you go on "https://mailu.domain.tpl/admin/antispam/#configuration", you will see that there are configuration files/options you can set through the WebUI. If set, and you restart the pod, all changes are lost because that is on the fs inside the pod only. This also applies to docker-compose I bet.
```
/etc/rspamd/local.d # df -h .
Filesystem                Size      Used Available Use% Mounted on
overlay                 109.0G     24.5G     79.0G  24% /
```
Regarding the filesystems inside the pods, they are all there except for the overrides, as in kubernetes we do that with configmap's (which is easier to deal with).


And - if we let it be deployed by helm as is, the resulting directory structure is as follows:
```
$ ls -l /var/lib/rancher/k3s/storage/pvc-f9e954b6-469c-44ee-bfaa-61d7ab2ddbd6_mailu-mailserver_mailu-storage
total 48
drwxrwxrwx  2 root             root      4096 Nov 15 13:44 admin
drwxrwxrwx  2 root             root      4096 Nov 15 13:44 clamav
drwxrwxrwx  2 root             root      4096 Nov 15 13:44 dkim
drwxrwxrwx  2 root             root      4096 Nov 15 13:44 dovecotdata
drwxrwxrwx  2 mail             man       4096 Nov 15 13:44 dovecotmail
drwxr-xr-x 16 root             root      4096 Nov 15 13:44 mailqueue
drwxrwxrwx  5 systemd-coredump root      4096 Nov 15 13:44 mysql
drwxrwxrwx  2 systemd-coredump root      4096 Nov 15 13:44 redis
drwxrwxrwx  3 www-data         www-data  4096 Nov 15 13:47 roundcube
drwxrwxrwx  2 root             root     12288 Nov 15 13:47 rspamd
```
Check the directory modes -> 777 except for mailqueue. Reason I do define that manually.

**Comment by micw** [comment] 2021-11-15 14:01
> > What is also important is that rspamd needs a **static** hostname. If the hostname is not static, then history is not retained on container recreation. This is a limitation of rspamd. Possibly the helm-chart already does this. I did not check this.
> 
> Nope. The helm-chart does not take that into account. That would require 1 thing to be changed, and 1 to be added.
> 
> ```
> apiVersion: apps/v1
> kind: StatefulSet
> metadata:
>   name: mailu-rspamd
>   namespace: mailu-mailserver  
> spec:
>   serviceName: "mailu-rspamd"
>   selector:
>     matchLabels:
>       app: mailu
>       component: rspamd
> ```
> 
> The Kind needs to be changed to "StatefulSet", and we need to add the serviceName to be something, just below the spec tag.
> 
> We should also add the possibility to make the /etc/rspamd/local.d/maps.d in the rspamd folder to point to a persistent directory? Currently, all configuration to the rspamd through the spam-UI won't survive a restart of the pod. At least with that, we'd have the local.d/maps.d which would remain.

The helm chart sets `hostname: rspamd``which results in the same name for all instances.

**Comment by micw** [comment] 2021-11-15 14:02
Regarding the storage, should we move this into a different issue?

**Comment by HaleyACS** [comment] 2021-11-15 14:25
> Regarding the storage, should we move this into a different issue?

Probably, yes.

**Comment by HaleyACS** [comment] 2021-11-15 14:29
> The helm chart sets `hostname: rspamd``which results in the same name for all instances.

Well, if I use the "default" way, I don't have the history in my rspamd UI (This is my 1.8 deployment/Production I tested this).

**Comment by micw** [comment] 2021-11-15 18:49
> > The helm chart sets `hostname: rspamd``which results in the same name for all instances.
> 
> Well, if I use the "default" way, I don't have the history in my rspamd UI (This is my 1.8 deployment/Production I tested this).

What is that "default way"?

**Comment by HaleyACS** [comment] 2021-11-15 20:13
> > > The helm chart sets `hostname: rspamd``which results in the same name for all instances.
> > 
> > 
> > Well, if I use the "default" way, I don't have the history in my rspamd UI (This is my 1.8 deployment/Production I tested this).
> 
> What is that "default way"?

Without creating the PVC manually upfront.

**Comment by HaleyACS** [comment] 2021-11-16 15:14
Default way is using plain helm and let it handle the PV/PVC.

**Comment by micw** [comment] 2021-12-08 19:03
I'm staring a new branch to pick up everything related to this.

> It looks like not all mappings are in sync.

I'm removing the dkim from rspamd. For overrides, there are already options for some services. Feel free to add a PR if you need additional one. Overrides in the chart will be no pvc mappings but configmaps.

> So as /data is defined, everything is in there. But rspamd local configuration as in /etc/rspamd/local.d is not.

I think I should also add this, but the settings will get lost one more time on next redeploy.

> Well, if I use the "default" way, I don't have the history in my rspamd UI

I re-verified this on my setup and cannot reproduce. If it occurs to you, please open a new issue with more details.

**Comment by micw** [comment] 2022-02-11 14:21
I'm closing this because the 1.9 fixes branch is merged. If I missed anything, please open new individual issues.

**Closed by micw** 2022-02-11 14:21 UTC
Labels: bug
